# 数据库配置
mysql:
  host: localhost
  port: 3306
  db:
  user:
  password:
  log_level: dev #日志登记

# 系统相关配置
system:
  host: localhost
  port: 9527
  env: dev #研发环节
# 日志
logger:
  level: info
  prefix: '[wheat_waves]' #前缀
  director: log
  show_line: true # 是否显示行号
  log_in_console: true #是否显示文件路径